extends Control

signal SelectedTransaction(button_pressed, trans_view_p);

@export var disalbed : bool = false;

const ENABLE_COLOR = Color("FFFFFF");
const DISABLE_COLOR = Color("989898");

@onready var background_color = %BackgroundColor;
@onready var date_acquired = %DateAcquired;
@onready var number_of_coins = %NumberOfCoins;
@onready var exchange_price = %ExchangePrice;
@onready var credit_amount = %CreditAmount;
@onready var debit_amount = %DebitAmount;
@onready var selected_trans = %SelectedTrans;

var trans_data : Transaction = null;

func _ready():
	clear_data();

func clear_data():
	date_acquired.text = "";
	number_of_coins.text = "";
	exchange_price.text = "";
	credit_amount.text = "";
	debit_amount.text = "";

func enable_trans():
	disalbed = false;
	date_acquired.modulate = ENABLE_COLOR;
	number_of_coins.modulate = ENABLE_COLOR;
	exchange_price.modulate = ENABLE_COLOR;
	credit_amount.modulate = ENABLE_COLOR;
	debit_amount.modulate = ENABLE_COLOR;
	selected_trans.modulate = ENABLE_COLOR;

func disalbe_trans():
	disalbed = true;
	date_acquired.modulate = DISABLE_COLOR;
	number_of_coins.modulate = DISABLE_COLOR;
	exchange_price.modulate = DISABLE_COLOR;
	credit_amount.modulate = DISABLE_COLOR;
	debit_amount.modulate = DISABLE_COLOR;
	selected_trans.modulate = DISABLE_COLOR;

# Fill out the transaction.
func set_trans_data(transaction_p):
	# Enable the transaction.
	enable_trans();
	
	trans_data = transaction_p;
	if transaction_p.date_m != null:
		date_acquired.text = String(transaction_p.date_m);
	number_of_coins.text = Utility.format_decimal("", transaction_p.number_of_coins_m);
	exchange_price.text = "$" + Utility.format_decimal("%3.2f", transaction_p.exchange_price_m);
	if(transaction_p.is_credit_m == true):
		credit_amount.text = "$" + Utility.format_decimal("%3.2f", transaction_p.amount_m);
	else:
		debit_amount.text = "$" + Utility.format_decimal("%3.2f", transaction_p.amount_m);
	
	# Disable Autogenerated Transactions
	if trans_data.trans_type_m == Transaction.TransactionType.GENERATED_TRANS:
		disalbe_trans();
	
	# Disable sold transactions.
	if trans_data.is_sold_m:
		disalbe_trans();

# Get the number of coins for the current transaction.
func get_number_of_coins():
	return trans_data.number_of_coins_m;

# Get the amount paid.
func get_amount_paid():
	return trans_data.amount_m;

# Flag to check if a row was selected.
func is_selected():
	return selected_trans.button_pressed;

# Get weither the transaction is a credit or debit.
func is_credit_trans():
	return trans_data.is_credit_m;

# Select a transaction.
func select_transaction(is_selected_p):
	background_color.visible = is_selected_p;
	selected_trans.button_pressed = is_selected_p;

# Selected the individual transaction.
func _on_SelectedTrans_toggled(button_pressed_p):
	emit_signal("SelectedTransaction", button_pressed_p, self);

# User clicked on the whole row.
func _on_CenterContainer_gui_input(event):
	if event is InputEventMouseButton:
		if event.button_index == MOUSE_BUTTON_LEFT and event.pressed:
			select_transaction(!selected_trans.button_pressed);
